<?php

/**
 * @file
 * Contains farm_inventory_views.module.
 */

use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_view().
 */
function farm_inventory_views_views_pre_view(ViewExecutable $view, string $display_id, array &$args): void {

  // Add quantity field to farm_asset view.
  if ($view->id() === 'farm_asset') {
    $view->addHandler($display_id, 'field', 'asset', 'inventory', [
      'alter' => [],
      'id' => 'inventory',
      'field' => 'inventory',
      'plugin_id' => 'asset_inventory',
      'label' => t('Quantity'),
      'type' => 'inventory',
    ]);
  }

}
